#!/usr/bin/env bash

# prototype-kicad-project-ci-cd
#
# Copyright 2021, Andrew Countryman <apcountryman@gmail.com> and the
# prototype-kicad-project-ci-cd contributors
#
# You may redistribute and modify this documentation and make products using it under the
# terms of the CERN-OHL-P v2 (https:/cern.ch/cern-ohl). This documentation is distributed
# WITHOUT ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING OF MERCHANTABILITY, SATISFACTORY
# QUALITY AND FITNESS FOR A PARTICULAR PURPOSE. Please see the CERN-OHL-P v2 for
# applicable conditions.

# File: git/hooks/pre-commit
# Description: Git pre-commit hook script for the prototype-kicad-project-ci-cd
#       repository.

function message()
{
    local -r content="$1"

    echo -n "$mnemonic: $content"
}

function errors_found()
{
    echo "error(s) found"
}

function error()
{
    local -r message="$1"

    ( >&2 echo "$mnemonic: $message" )
}

function abort()
{
    if [[ "$#" -gt 0 ]]; then
        local -r message="$1"

        error "$message, aborting"
    fi

    exit 1
}

function display_help_text()
{
    echo "NAME"
    echo "    $mnemonic - Ensure:"
    echo "        - Filenames are portable"
    echo "        - No whitespace errors are present"
    echo "        - No script errors are present"
    echo "SYNOPSIS"
    echo "    $mnemonic --help"
    echo "    $mnemonic --version"
    echo "    $mnemonic"
    echo "OPTIONS"
    echo "    --help"
    echo "        Display this help text."
    echo "    --version"
    echo "        Display the version of this script."
    echo "EXAMPLES"
    echo "    $mnemonic --help"
    echo "    $mnemonic --version"
    echo "    $mnemonic"
}

function display_version()
{
    echo "$mnemonic, version $version"
}

function ensure_filenames_are_portable()
{
    message "checking for non-portable (non-ASCII) filenames ... "

    if [[ $( git -C "$repository" diff --cached --name-only --diff-filter=A -z "$against" | LC_ALL=C tr -d '[ -~]\0' | wc -c ) != 0 ]]; then
        errors_found
        error "aborting commit due to non-portable (non-ASCII) filename(s)"
        abort
    fi

    echo "none"
}

function ensure_no_whitespace_errors_are_present()
{
    message "checking for whitespace errors .................... "

    if ! git -C "$repository" diff-index --check --cached "$against" -- > "/dev/null" 2>&1; then
        errors_found
        error "aborting commit due to whitespace error(s), listed below"
        git -C "$repository" diff-index --check --cached "$against" --
        abort
    fi

    echo "none"
}

function ensure_no_script_errors_are_present()
{
    message "checking for script errors ........................ "

    local scripts; mapfile -t scripts < <( git -C "$repository" ls-files ':!:prototype-kicad-library-ci/' ':!:utilities/' | xargs -r -d '\n' -I '{}' find "$repository/{}" -executable ); readonly scripts

    if ! shellcheck "${scripts[@]}" > "/dev/null" 2>&1; then
        errors_found
        error "aborting commit due to script error(s), listed below"
        shellcheck "${scripts[@]}"
        abort
    fi

    echo "none"
}

function main()
{
    local -r script=$( readlink -f "$0" )
    local -r mnemonic=$( basename "$script" )
    local -r hooks=$( dirname "$script" )
    local -r repository=$( readlink -f "$hooks/../.." )
    local -r version=$( git -C "$repository" describe --match=none --always --dirty --broken )

    while [[ "$#" -gt 0 ]]; do
        local argument="$1"; shift

        case "$argument" in
            --help)
                display_help_text
                exit
                ;;
            --version)
                display_version
                exit
                ;;
            --*)
                ;&
            -*)
                abort "'$argument' is not a supported option"
                ;;
            *)
                abort "'$argument' is not a valid argument"
                ;;
        esac
    done

    if git -C "$repository" rev-parse --verify HEAD > "/dev/null" 2>&1; then
        local -r against=HEAD
    else
        local -r against=$( git hash-object -t tree "/dev/null" )
    fi

    ensure_filenames_are_portable
    ensure_no_whitespace_errors_are_present
    ensure_no_script_errors_are_present
}

main "$@"
